name: fitnessapp

networks:
  dev-network:
    driver: bridge

services:
  dev-db:
    image: postgres:18.0-alpine3.22
    restart: always
    env_file:
      - ./.env.${ENVIRONMENT}
    # ports:
    #   - "5433:5432"
    networks:
      - dev-network
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # dev-test:
  #   image: postgres:18.0-alpine3.22
  #   restart: always
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "5434:5432"
  #   networks:
  #     - dev-network
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: Test1234!
  #     POSTGRES_DB: FitnessAppTestDB

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - dev-network
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    networks:
      - dev-network
    env_file:
      - ./.env.${ENVIRONMENT}
    depends_on:
      dev-db:
        condition: service_healthy
